### ISSUE TITLE
Non-polyfilling version

### ISSUE THREAD

**Issue by jfirebaugh** [mathiasbynens/String.fromCodePoint#4]
I'd like to be able to do `const stringFromCodePoint = require('string.fromCodePoint');` and not touch any global state.

Rationale: I'm writing a library. It needs to use the "string from codepoint" algorithm, but it shouldn't go around changing globals itself. For instance, the user may be polyfilling `String.fromCodePoint` themselves, with another implementation, and my library should not overwrite that.

**Comment by mathiasbynens** [comment]
> For instance, the user may be polyfilling `String.fromCodePoint` themselves, with another implementation, and my library should not overwrite that.

That’s not what would happen: https://github.com/mathiasbynens/String.fromCodePoint/blob/880fb77864ecba1dd5ac32e9607ceb0f00c0028f/fromcodepoint.js#L2
